### ISSUE TITLE
[VSC] OScript запускатель

### ISSUE THREAD

**Issue by vsuh** [nixel2007/1c-syntax#3]
таки, определились с репозиторием? тогда сюда.
При редактировании в **vsc** `*.os` файла нажать `F1` написать `task` и нажать `Enter`

Попадаем в инструмент **Tasks: Configure task runner** который реализован в виде файла `tasks.json` в специальном каталоге `.vscode` текущего проекта. Вставить туда следующий текст:

**tasks.json**

```
{
"version": "0.1.0",
"windows": {
    "command": "oscript.exe"
},
"linux": {
    "command": "/opt/bin/oscript"
},
"isShellCommand": true,
// Show the output window only if unrecognized errors occur.
"showOutput": "silent",
"args": [
    "-encoding=utf-8"
],
"tasks": [
    {
        "taskName": "Compile",
        "args": [
            "-compile",
            "${file}"
        ],
        "echoCommand": true,
        "showOutput": "always",
        "suppressTaskName": true,
        "isBuildCommand": true
    },
    {
        "taskName": "Run",
        "args": [
            "${file}"
        ],
        //"echoCommand": true,
        "showOutput": "always",
        "suppressTaskName": true,
                 "problemMatcher": "$gulp-tsc",
        "isBuildCommand": true
    }
]
}
```

В результате в списке задач появится две задачи `Compile` и `Run` вызвать их можно опять же комбинацией `F1` `tasks: run task` или назначить комбинацию клавиш командой `File -> Preferences -> Keyboard Shortcuts` на команду `workbench.action.tasks.runTask`.

Кстати, выражение `"isBuildCommand": true` в задаче `Compile` обозначает, что ее можно запустить комбинацией `Ctrl-Shift-B`

Текст написан по мотивам [официальной документации на VSC](https://code.visualstudio.com/Docs/editor/tasks)

В следующий раз, уважаемые читатели, мы поговорим о настройке блока `problemMatcher`, которая позволит нам переходить к выражению в коде, вызвавшему ошибку.

**Comment by nixel2007** [comment]
@vsuh спасибо большое! Правильно ли я понимаю, что каталог `.vscode` можно включать в распространяемый package? То есть можно сделать объединенный пакет и для описания грамматики и для запускателей/отладчиков?

**Comment by vsuh** [comment]
У `VSC` есть глобальный (в $HOME) и локальный (в каталоге проекта) каталоги
`.vscode` файл `tasks.json` не может располагаться в глобальном
`~/.vscode`, только в локальном

**Comment by vsuh** [comment]
Отдельная история по `code snippets`.

Если мы решили присвоить языку `OneScript` код `onescript` и, соответственно, указали этот код в выражениях `name`, `contributes.languages.id`  и `contributes.grammars.language` файла `package.json`

![2015-12-03_11-40-15](https://cloud.githubusercontent.com/assets/12156293/11555648/e6cca53c-99b2-11e5-8f98-a1b739802361.jpg)

, то мы имеем полное право создать файл сниппетов **onescript.json** в каталоге `%userprofile%\AppData\Roaming\Code\User\snippets\` который будет действовать в файлах с выбранным языком  `onescript` примерно такого содержания, :

```
{
"Цикл для каждого": {
    "prefix": "дляк",
    "body": [
        "Для Каждого нн Из $1 Цикл",
        "    $2;",
        "КонецЦикла;"
    ],
    "description": "Цикл Для каждого нн Из..."
},
"Попытка с исключением": {
    "prefix": "попи",
    "body": [
        "Попытка",
        "   $1",
        "Исключение",
        "   Сообщить(ОписаниеОшибки());",
        "КонецИсключения;",
        "$2"
    ],
    "description": "попытка с исключением"
}
}
```

**Comment by nixel2007** [comment]
Можно даже создать сниппеты под стандартные шаблоны текста в конфигураторе... 
Можно ли в onescript.json делать группировку сниппетов по типу папок в шаблонах текста в 1с (Управляющие, Прикладные, Прочие и т.д.)? В том числе для последующей группировки в просмотрщике сниппетов (если он есть в vsc)

**Comment by vsuh** [comment]
кажется, нет, разве что, префиксами в имени, ключе или описании разметить визуально
